---

- name: Add WireGuard repository
  apt_repository:
    repo: "ppa:wireguard/wireguard"
    state: present
    update_cache: yes
  tags:
    - wg-install

- name: Install required packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - software-properties-common
    - linux-headers-{{ ansible_kernel }}
    - wireguard
  tags:
    - wg-install

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    reload: yes
  tags: wg-install
