---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  labels:
    service: adguard
spec:
  ports:
    - name: tcp
      port: 53
      targetPort: 53
      nodePort: 30110
      protocol: TCP
    - name: udp
      port: 53
      targetPort: 53
      nodePort: 30111
      protocol: UDP
  type: NodePort
  selector:
    service: adguard