namespace: adguard
resources:
  - namespace.yml
  - adguard/adguard-deployment.yml
  - adguard/adguard-service.yml
  - adguard/adguard-web-service.yml
  - dns-svc.yml
configMapGenerator:
  - name: app-config
    files:
      - AdGuardHome.yaml=configs/AdGuardHome.yml
patchesStrategicMerge:
  - patches/init-container.yml
  - patches/add-config-volume.yml
  - patches/nodeport-hardcode.yml
