kubekutr -c kubekutr.yml scaffold -o .
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
data:
  AdGuardHome.yaml: |-
    bind_host: 0.0.0.0
    bind_port: 3000
    users:
    - name: karan
      password: bullah
    language: ""
    rlimit_nofile: 0
    web_session_ttl: 720
    dns:
      bind_host: 0.0.0.0
      port: 53
      statistics_interval: 1
      querylog_enabled: true
      querylog_interval: 90
      querylog_memsize: 0
      protection_enabled: true
      blocking_mode: null_ip
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      bootstrap_dns: []
      all_servers: false
      edns_client_subnet: false
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts: []
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      cache_size: 4194304
      upstream_dns:
      - 1.1.1.1
      filtering_enabled: true
      filters_update_interval: 24
      parental_sensitivity: 0
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      rewrites: []
      blocked_services: []
    tls:
      enabled: false
      server_name: ""
      force_https: false
      port_https: 443
      port_dns_over_tls: 853
      allow_unencrypted_doh: false
      certificate_chain: ""
      private_key: ""
      certificate_path: ""
      private_key_path: ""
    filters:
    - enabled: true
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      name: AdGuard Simplified Domain Names filter
      id: 1
    - enabled: true
      url: https://adaway.org/hosts.txt
      name: AdAway
      id: 2
    - enabled: true
      url: https://hosts-file.net/ad_servers.txt
      name: hpHosts - Ad and Tracking servers only
      id: 3
    - enabled: true
      url: https://www.malwaredomainlist.com/hostslist/hosts.txt
      name: MalwareDomainList.com Hosts List
      id: 4
    user_rules: []
    dhcp:
      enabled: false
      interface_name: ""
      gateway_ip: ""
      subnet_mask: ""
      range_start: ""
      range_end: ""
      lease_duration: 86400
      icmp_timeout_msec: 1000
    clients: []
    log_file: ""
    verbose: false
    schema_version: 6
kind: ConfigMap
metadata:
  name: app-config-54ckbfb94d
  namespace: adguard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: adguard
    tier: dns
  name: adguard
  namespace: adguard
spec:
  ports:
  - name: dns-port
    port: 53
    protocol: TCP
    targetPort: dns-port
  - name: web-port
    port: 3000
    protocol: TCP
    targetPort: web-port
  selector:
    service: adguard
    tier: dns
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: adguard
    tier: dns
  name: adguard-dns
  namespace: adguard
spec:
  ports:
  - name: dot-port
    nodePort: 30100
    port: 53
    protocol: TCP
    targetPort: dns-port
  - name: dns-port
    port: 53
    protocol: UDP
    targetPort: dns-port
  selector:
    service: adguard
    tier: dns
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: adguard
    tier: web
  name: adguard-web
  namespace: adguard
spec:
  ports:
  - name: web-port
    nodePort: 30102
    port: 3000
    protocol: TCP
    targetPort: web-port
  selector:
    service: adguard
    tier: dns
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: adguard
    tier: dns
  name: adguard
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adguard
      tier: dns
  template:
    metadata:
      labels:
        service: adguard
        tier: dns
    spec:
      containers:
      - image: adguard/adguardhome:armhf-edge
        name: adguard
        ports:
        - containerPort: 3000
          name: web-port
        resources:
          limits:
            cpu: 180m
            memory: 200Mi
          requests:
            cpu: 90m
            memory: 100Mi
        volumeMounts:
        - mountPath: /config
          name: tmp-config-volume
        - mountPath: /app
          name: config-volume
      initContainers:
      - command:
        - sh
        - -c
        - cp /config/AdGuardHome.yaml /app
        image: balenalib/armv7hf-debian:run
        name: init-adguard
        volumeMounts:
        - mountPath: /config
          name: tmp-config-volume
        - mountPath: /app
          name: config-volume
      volumes:
      - emptyDir: {}
        name: config-volume
      - configMap:
          name: app-config-54ckbfb94d
        name: tmp-config-volume
