---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s-control.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from control node
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store control node-token
  set_fact:
   k3s_cluster_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Print cluster node token
  debug:
    msg: "{{ k3s_cluster_token }}"

- name: Restore node-token file access 
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

# - name: Copy config file to user home directory
#   copy:
#     src: /etc/rancher/k3s/k3s.yaml
#     dest: /home/{{ ansible_user }}/.kube/config
#     remote_src: yes
#     owner: "{{ ansible_user }}"

- name: Set server address
  set_fact:
    k3s_server_address: "https://{{ ansible_default_ipv4.address }}:6443"
  run_once: yes

- name: Print server address
  debug:
    msg: "{{ k3s_server_address }}"

- name: Replace https://localhost:6443 with {{k3s_server_address}}
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: 'https://localhost:6443'
    replace: '{{k3s_server_address}}'
