global:
  scrape_interval: 30s
  external_labels:
    hydra_component: "floyd"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "ispmonitor"
    scrape_interval: 60s
    static_configs:
      - targets: ["100.94.241.54:9283"] # RPi telegraf Agent

  - job_name: caddy-public
    scrape_interval: 60s
    static_configs:
      - targets: ['caddy_public:2019']

  - job_name: caddy-internal
    scrape_interval: 60s
    static_configs:
      - targets: ['caddy_internal:2019']
