---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    service: nginx
spec:
  ports:
  - port: 80
    name: proxy-port
    targetPort: proxy-port
    protocol: TCP
  type: NodePort
  selector:
    tier: proxy
    service: nginx
