---
apiVersion: v1
kind: Service
metadata:
  name: gitea-nodeport
  labels:
    service: gitea
spec:
  ports:
  - port: 3000
    name: web
    targetPort: web-port
    nodePort: 30300
    protocol: TCP
  - port: 22
    name: ssh
    targetPort: ssh-port
    nodePort: 30222
    protocol: TCP
  type: NodePort
  selector:
    service: gitea
