---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    service: gitea
    tier: web
spec:
  ports:
  - port: 3000
    name: web-port
    targetPort: web-port
    protocol: TCP
  - port: 22
    name: ssh-port
    targetPort: ssh-port
    protocol: TCP
  type: ClusterIP
  selector:
    service: gitea
    tier: web
