---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    service: gitea
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gitea
      tier: web
  template:
    metadata:
      labels:
        service: gitea
        tier: web
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.11
        ports:
        - containerPort: 3000
          name: web-port
        - containerPort: 22
          name: ssh-port
        resources:
          requests:
            memory: 150Mi
            cpu: 200m
          limits:
            memory: 350Mi
            cpu: 400m
        volumeMounts:
        - mountPath: /data
          name: data
      nodeSelector:
        kubernetes.io/arch: amd64