- name: Clouflare auth token required
  fail:
    msg: "You must include a Clouflare auth token. Set a `cloudflare_api_token` ansible-vault encrypted variable."
  when: cloudflare_api_token is not defined

- name: Create caddy project directory if it does not exist
  file:
    path: "{{caddy_project_dir}}"
    state: directory

- name: Copy caddy docker-compose
  template:
    src: Caddyfile.j2
    dest: "{{caddy_project_dir}}/Caddyfile"

- name: Copy caddy docker-compose
  template:
    src: caddy-docker-compose.yml.j2
    dest: "{{caddy_project_dir}}/docker-compose.yml"

- name: Start docker-compose
  shell:
    cmd: docker-compose up -d
    chdir: "{{caddy_project_dir}}"
