---
apiVersion: v1
kind: Service
metadata:
  name: adguard
  labels:
    service: adguard
    tier: dns
spec:
  ports:
  - port: 53
    name: dns-port
    targetPort: dns-port
    protocol: TCP
  - port: 3000
    name: web-port
    targetPort: web-port
    protocol: TCP
  type: ClusterIP
  selector:
    service: adguard
    tier: dns
