---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  labels:
    service: adguard
    tier: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adguard
      tier: dns
  template:
    metadata:
      labels:
        service: adguard
        tier: dns
    spec:
      containers:
      - name: adguard
        image: adguard/adguardhome:armhf-edge
        ports:
        - containerPort: 53
          name: dns-port
        ports:
        - containerPort: 3000
          name: web-port
        resources:
          requests:
            memory: 100Mi
            cpu: 90m
          limits:
            memory: 200Mi
            cpu: 180m
        volumeMounts:
        - mountPath: /config
          name: tmp-config-volume
        - mountPath: /app
          name: config-volume
      volumes:
        - name: tmp-config-volume
        - name: config-volume
