---
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
  labels:
    service: adguard
    tier: web
spec:
  ports:
  - port: 3000
    name: web-port
    targetPort: web-port
    protocol: TCP
  type: NodePort
  selector:
    tier: dns
    service: adguard
