---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  labels:
    service: adguard
    tier: dns
spec:
  ports:
  - port: 53
    name: dot-port
    targetPort: dns-port
    protocol: TCP
  - port: 53
    name: dns-port
    targetPort: dns-port
    protocol: UDP
  type: NodePort
  selector:
    tier: dns
    service: adguard
