---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    service: unbound
    tier: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      service: unbound
      tier: dns
  template:
    metadata:
      labels:
        service: unbound
        tier: dns
    spec:
      containers:
      - name: unbound
        image: mvance/unbound-rpi:latest
        ports:
        - containerPort: 53
          name: dns-port
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 80m
