---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  labels:
    service: unbound
    tier: dns
spec:
  ports:
  - port: 53
    name: dns-port
    targetPort: dns-port
    protocol: TCP
  type: ClusterIP
  selector:
    service: unbound
    tier: dns
