# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: adguard-dns
# spec:
#   ports:
#   - port: 53
#     nodePort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
spec:
  ports:
  - port: 3000
    nodePort: 30102
